### ISSUE TITLE
how to render

### ISSUE THREAD

**Issue by Calsia** [fnzhan/Illumination-Estimation#10]
hi， your work is so beautiful!and thks for your code.
i want to know what should i do to use the result in blender?
thks for any reply

**Comment by Calsia** [comment]
The lighting estimaiton performance is evaluated by using the predicted illumination map as the environment light in Blender.

**Comment by Calsia** [comment]
by the way, i try to test it use my own jpg .something wrong happened.
self.fc = nn.Linear(8208, 1024) doesn't match.

**Comment by fnzhan** [comment]
> The lighting estimaiton performance is evaluated by using the predicted illumination map as the environment light in Blender. i see this in `readme.md`，but i can't understand

Hi, you should replace the environment map in blender with the predicted illumination map
![Snipaste_2021-12-07_20-26-56](https://user-images.githubusercontent.com/21986728/145028986-2c63d9f4-0296-4679-9d42-b71fd0bc2a28.png)
.

**Comment by fnzhan** [comment]
> 

Of course, the default size should be 256 * 192

**Comment by fnzhan** [comment]
> 

Of course, the default size should be 256 * 192.

**Comment by Calsia** [comment]
thanks a lot. 
one more question( i wish). 
![图片](https://user-images.githubusercontent.com/13194457/145143898-bbde0c79-a44e-4563-831a-ebebb7d70f13.png)
in `RegressionNetwork/test.py`, u set ln is 42. but the model ouput the `distribution_pred` with size 96.
how could i fix them

**Comment by fnzhan** [comment]
> 

You may just change ln to 96.

**Comment by Calsia** [comment]
Of course,  i have tried.
but the `dirs` will not match, which is used to generate a `.exr` in your code.
![图片](https://user-images.githubusercontent.com/13194457/145145523-a425efab-f31f-4eb4-8b00-5bbf128c3c41.png)

**Comment by Calsia** [comment]
![图片](https://user-images.githubusercontent.com/13194457/145145638-12b10255-8146-443b-968f-c053a41dc19a.png)

**Comment by fnzhan** [comment]
> 

I have updated the code, should replace util.polyhedron(1) with util.sphere_points(ln) 
https://github.com/fnzhan/Illumination-Estimation/blob/b0b7832a842c7450539c0b338a4f194e06a3a1dc/RegressionNetwork/test.py#L59

**Comment by Calsia** [comment]
that's  totally what  i do.
finally, i want use the `.exr`(i think is the  illumination map mentioned above) as light to render my own scene. 
but how could i align it with my model?

**Comment by Calsia** [comment]
by the way，these are my input and result .it seems not very good. do u have any suggestions to improve it?

![图片](https://user-images.githubusercontent.com/13194457/145152197-dea51f15-21ab-42d3-9d3d-76f71d7b9e87.png)

![图片](https://user-images.githubusercontent.com/13194457/145152511-ccac1c73-f3ab-4e7e-8a5b-b7e7df849577.png)

**Comment by fnzhan** [comment]
> 

The model is only trained on Laval Indoor datasets,  which only 2000 panoramas. Thus, it is hard to generalized to other scenes.

**Comment by Calsia** [comment]
thks a lot for your reply
