### ISSUE TITLE
How to make the luminance of HDR datasets in the same scale?

### ISSUE THREAD

**Issue by Mrwjm** [fnzhan/Illumination-Estimation#14]
The luminance of HDR panoramas in the Laval datasets maybe in the different scales.Did you make the HDR panoramas in the same scale? How to do that?

**Comment by fnzhan** [comment]
For the processing of training data in distribution-based representation, I don't adjust the luminance scale.

For the visualization of illumination map, the luminance intensity should be scaled through tone-mapping, please check here: https://github.com/fnzhan/Illumination-Estimation/blob/d93bff75edf43c42277182cb0a53509d66d76bad/RegressionNetwork/util.py#L29

**Comment by Mrwjm** [comment]
OK，thanks a lot.
