### ISSUE TITLE
benchmark in GMLight

### ISSUE THREAD

**Issue by yaodao-x** [fnzhan/Illumination-Estimation#5]
Hi, fnZhang.
Do you reproduce the paper “Fast Spatially-Varying Indoor Lighting Estimation“ as reference, or in any other ways to get the predictions.

**Comment by fnzhan** [comment]
Hi, we send our testing images to the author and ask for the testing results.

**Comment by yaodao-x** [comment]
Thank you for your  immediate answer. It's very helpful to me.
