### ISSUE TITLE
The input parameters for training of the Neural Projector of EMLight

### ISSUE THREAD

**Issue by Lingstreasure** [fnzhan/Illumination-Estimation#8]
Hi fnzhan:
      Could you please tell me which illumination map parameters you used as input during the training of the Neural Projector of EMlight, the parameters predicted by Regression network or the parameters of Ground Truth ？

**Comment by cyjouc** [comment]
hi,do you find the regression network ,the same image envalation model ,but output is different.as where, the first cov2 of network output is yet different!

**Comment by fnzhan** [comment]
We start with the Ground Truth, then turn to the predicted results.

**Comment by Lingstreasure** [comment]
> We start with the Ground Truth, then turn to the predicted results.

Thanks for your reply. Thank you.
